import './globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import Container from '@/components/layouts/Container'
import { cn } from '@/lib/utils'
import RecoilProvider from '@/providers/RecoilProvider'
import TanstackProvider from '@/providers/TanstackProvider'
import { ThemeProvider } from '@/providers/ThemeProvider'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased w-full max-w-375pxr flex flex-col justify-center self-center mx-auto',
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="default"
          enableSystem
          disableTransitionOnChange
        >
          <RecoilProvider>
            <TanstackProvider>
              <Container>{children}</Container>
            </TanstackProvider>
          </RecoilProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
