#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
BRANCH_NAME=$(git branch --show-current)
JIRA_ISSUE=$(echo $BRANCH_NAME | grep -oE '^[^-]+-[^-]+')
npx --no -- commitlint --edit "$1"

if [ -n "$JIRA_ISSUE" ]; then
    COMMIT_MSG_FILE=$(git rev-parse --git-path COMMIT_EDITMSG)
    COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
    if ! echo "$COMMIT_MSG" | grep -qE "^$JIRA_ISSUE"; then
        echo "[$JIRA_ISSUE] $COMMIT_MSG" > "$COMMIT_MSG_FILE"
    fi
fi


